#!/usr/bin/env python3
"""Script to bulk-add cricketers to the CricStar bot database."""
import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ADMIN_PANEL_DIR = os.path.join(BASE_DIR, "admin_panel")
sys.path.insert(0, ADMIN_PANEL_DIR)
sys.path.insert(0, BASE_DIR)
os.environ["DJANGO_SETTINGS_MODULE"] = "admin_panel.settings.cricstar"

import django
django.setup()

from bd_models.models import Ball, Regime, Economy

regime = Regime.objects.first()
economy = Economy.objects.first()

if not regime:
    print("No regime found! Run migrations first.")
    sys.exit(1)

CRICKETERS = [
    (0.01, "ODI World Cup"),
    (0.05, "VDR"),
    (0.05, "Sachin Tendulkar"),
    (0.05, "India"),
    (0.05, "Australia"),
    (0.08, "Sir Viv Richards"),
    (0.08, "T20 World Cup"),
    (0.1, "New Zealand"),
    (0.1, "West Indies"),
    (0.1, "Lords"),
    (0.1, "Melbourne"),
    (0.1, "Ms Dhoni"),
    (0.1, "Rohit Sharma (T20 WC)"),
    (0.1, "Virat Kohli"),
    (0.1, "Brian Lara"),
    (0.1, "Dale Steyn"),
    (0.1, "Steve Smith"),
    (0.2, "Sir Don Bradman"),
    (0.2, "Jacques Kallis"),
    (0.2, "Muttiah Muralitharan"),
    (0.2, "Shane Warne"),
    (0.2, "Wasim Akram"),
    (0.2, "Glenn McGrath"),
    (0.2, "Ricky Ponting"),
    (0.2, "Sir Garfield Sobers"),
    (0.2, "Imran Khan"),
    (0.2, "Kapil Dev"),
    (0.3, "AB de Villiers"),
    (0.3, "Kumar Sangakkara"),
    (0.3, "Adam Gilchrist"),
    (0.3, "Waqar Younis"),
    (0.3, "Sir Richard Hadlee"),
    (0.3, "Sunil Gavaskar"),
    (0.3, "Rahul Dravid"),
    (0.3, "Allan Border"),
    (0.3, "VVS Laxman"),
    (0.3, "Anil Kumble"),
    (0.4, "Kane Williamson"),
    (0.4, "Joe Root"),
    (0.4, "James Anderson"),
    (0.4, "Stuart Broad"),
    (0.4, "Shoaib Akhtar"),
    (0.4, "Brett Lee"),
    (0.4, "Virender Sehwag"),
    (0.4, "Yuvraj Singh"),
    (0.4, "Sourav Ganguly"),
    (0.4, "Mahela Jayawardene"),
    (0.5, "Matthew Hayden"),
    (0.5, "Justin Langer"),
    (0.5, "Hashim Amla"),
    (0.5, "Faf du Plessis"),
    (0.5, "Chris Gayle"),
    (0.5, "Kevin Pietersen"),
    (0.5, "Mitchell Starc"),
    (0.5, "Pat Cummins"),
    (0.5, "Trent Boult"),
    (0.5, "Tim Southee"),
    (0.6, "Jasprit Bumrah"),
    (0.6, "Ravichandran Ashwin"),
    (0.6, "Ravindra Jadeja"),
    (0.6, "David Warner"),
    (0.6, "Shikhar Dhawan"),
    (0.6, "Gautam Gambhir"),
    (0.6, "Zaheer Khan"),
    (0.6, "Harbhajan Singh"),
    (0.6, "Michael Clarke"),
    (0.6, "Graeme Smith"),
    (0.7, "Ben Stokes"),
    (0.7, "Jos Buttler"),
    (0.7, "Jonny Bairstow"),
    (0.7, "Quinton de Kock"),
    (0.7, "Kagiso Rabada"),
    (0.7, "Shakib Al Hasan"),
    (0.7, "Rashid Khan"),
    (0.7, "Babar Azam"),
    (0.7, "Mohammad Rizwan"),
    (0.7, "Shaheen Afridi"),
    (0.8, "Jason Holder"),
    (0.8, "Kieron Pollard"),
    (0.8, "Dwayne Bravo"),
    (0.8, "Sunil Narine"),
    (0.8, "Lasith Malinga"),
    (0.8, "Sanath Jayasuriya"),
    (0.8, "Tillakaratne Dilshan"),
    (0.8, "Chaminda Vaas"),
    (0.8, "Ross Taylor"),
    (0.8, "Martin Guptill"),
    (0.9, "Eoin Morgan"),
    (0.9, "Aaron Finch"),
    (0.9, "Glenn Maxwell"),
    (0.9, "Marcus Stoinis"),
    (0.9, "Hardik Pandya"),
    (0.9, "KL Rahul"),
    (0.9, "Rishabh Pant"),
    (0.9, "Shreyas Iyer"),
    (0.9, "Suryakumar Yadav"),
    (0.9, "Mohammed Shami"),
    (1.0, "Mohammed Siraj"),
    (1.0, "Kuldeep Yadav"),
    (1.0, "Yuzvendra Chahal"),
    (1.0, "Ishant Sharma"),
    (1.0, "Ajinkya Rahane"),
    (1.0, "Cheteshwar Pujara"),
    (1.0, "Umesh Yadav"),
    (1.0, "Bhuvneshwar Kumar"),
    (1.0, "Mitchell Johnson"),
    (1.0, "Morne Morkel"),
    (1.5, "Vernon Philander"),
    (1.5, "Jofra Archer"),
    (1.5, "Mark Wood"),
    (1.5, "Chris Woakes"),
    (1.5, "Moeen Ali"),
    (1.5, "Adil Rashid"),
    (1.5, "Sam Curran"),
    (1.5, "David Miller"),
    (1.5, "Rassie van der Dussen"),
    (1.5, "Temba Bavuma"),
    (2.0, "Lungi Ngidi"),
    (2.0, "Anrich Nortje"),
    (2.0, "Heinrich Klaasen"),
    (2.0, "Aiden Markram"),
    (2.0, "Devon Conway"),
    (2.0, "Tom Latham"),
    (2.0, "Daryl Mitchell"),
    (2.0, "Mitchell Santner"),
    (2.0, "Ish Sodhi"),
    (2.0, "Lockie Ferguson"),
    (2.5, "Matt Henry"),
    (2.5, "Colin de Grandhomme"),
    (2.5, "Kusal Mendis"),
    (2.5, "Dhananjaya de Silva"),
    (2.5, "Dushmantha Chameera"),
    (2.5, "Wanindu Hasaranga"),
    (2.5, "Dasun Shanaka"),
    (2.5, "Pathum Nissanka"),
    (2.5, "Mushfiqur Rahim"),
    (2.5, "Tamim Iqbal"),
    (3.0, "Mahmudullah"),
    (3.0, "Mustafizur Rahman"),
    (3.0, "Mehidy Hasan Miraz"),
    (3.0, "Litton Das"),
    (3.0, "Taskin Ahmed"),
    (3.0, "Fakhar Zaman"),
    (3.0, "Imam-ul-Haq"),
    (3.0, "Haris Rauf"),
    (3.0, "Naseem Shah"),
    (3.0, "Shadab Khan"),
    (4.0, "Alex Carey"),
    (4.0, "Travis Head"),
    (4.0, "Marnus Labuschagne"),
    (4.0, "Cameron Green"),
    (4.0, "Josh Hazlewood"),
    (4.0, "Nathan Lyon"),
    (4.0, "Usman Khawaja"),
    (4.0, "Dawid Malan"),
    (4.0, "Harry Brook"),
    (4.0, "Ben Duckett"),
    (5.0, "Ruturaj Gaikwad"),
    (5.0, "Yashasvi Jaiswal"),
    (5.0, "Shubman Gill"),
    (5.0, "Ishan Kishan"),
    (5.0, "Sanju Samson"),
    (5.0, "Washington Sundar"),
    (5.0, "Axar Patel"),
    (5.0, "Shardul Thakur"),
    (5.0, "Deepak Chahar"),
    (5.0, "Arshdeep Singh"),
    (6.0, "Mukesh Kumar"),
    (6.0, "Prasidh Krishna"),
    (6.0, "Navdeep Saini"),
    (6.0, "T Natarajan"),
    (6.0, "Rahul Chahar"),
    (6.0, "Ravi Bishnoi"),
    (6.0, "Avesh Khan"),
    (6.0, "Khaleel Ahmed"),
    (6.0, "Shivam Dube"),
    (6.0, "Rinku Singh"),
    (7.0, "Tilak Varma"),
    (7.0, "Jitesh Sharma"),
    (7.0, "Rajat Patidar"),
    (7.0, "Devdutt Padikkal"),
    (7.0, "Prithvi Shaw"),
    (7.0, "Manish Pandey"),
    (7.0, "Kedar Jadhav"),
    (7.0, "Vijay Shankar"),
    (7.0, "Stuart Binny"),
    (7.0, "Yusuf Pathan"),
    (8.0, "Irfan Pathan"),
    (8.0, "Munaf Patel"),
    (8.0, "Sreesanth"),
    (8.0, "RP Singh"),
    (8.0, "Ashish Nehra"),
    (8.0, "Piyush Chawla"),
    (8.0, "Amit Mishra"),
    (8.0, "Pragyan Ojha"),
    (8.0, "Parthiv Patel"),
    (8.0, "Dinesh Karthik"),
    (9.0, "Wriddhiman Saha"),
    (9.0, "Jaydev Unadkat"),
    (9.0, "Mohit Sharma"),
    (9.0, "Sandeep Sharma"),
    (9.0, "Siddharth Kaul"),
    (9.0, "Barinder Sran"),
    (9.0, "Rishi Dhawan"),
    (9.0, "Gurkeerat Singh Mann"),
    (9.0, "Faiz Fazal"),
    (9.0, "Naman Ojha"),
    (10.0, "Karun Nair"),
    (10.0, "Hanuma Vihari"),
    (10.0, "Mayank Agarwal"),
    (10.0, "Abhimanyu Easwaran"),
    (10.0, "Priyank Panchal"),
    (10.0, "Sheldon Jackson"),
    (10.0, "Jalaj Saxena"),
    (10.0, "Shahbaz Nadeem"),
    (10.0, "Karn Sharma"),
    (10.0, "Parvez Rasool"),
    (11.0, "Ashton Agar"),
    (11.0, "Matthew Renshaw"),
    (11.0, "Peter Handscomb"),
    (11.0, "Marcus Harris"),
    (11.0, "Jhye Richardson"),
    (11.0, "Riley Meredith"),
    (11.0, "Nathan Ellis"),
    (11.0, "Sean Abbott"),
    (11.0, "Daniel Sams"),
    (11.0, "Jason Behrendorff"),
    (12.0, "Kane Richardson"),
    (12.0, "Andrew Tye"),
    (12.0, "Billy Stanlake"),
    (12.0, "Ben McDermott"),
    (12.0, "D'Arcy Short"),
    (12.0, "Chris Lynn"),
    (12.0, "Ben Cutting"),
    (12.0, "Moises Henriques"),
    (12.0, "Dan Christian"),
    (12.0, "James Faulkner"),
    (13.0, "Tom Banton"),
    (13.0, "Tom Curran"),
    (13.0, "Craig Overton"),
    (13.0, "Jamie Overton"),
    (13.0, "Saqib Mahmood"),
    (13.0, "Brydon Carse"),
    (13.0, "Luke Wood"),
    (13.0, "Richard Gleeson"),
    (13.0, "Matt Parkinson"),
    (13.0, "Mason Crane"),
    (14.0, "Dom Bess"),
    (14.0, "Haseeb Hameed"),
    (14.0, "Keaton Jennings"),
    (14.0, "Sam Billings"),
    (14.0, "James Vince"),
    (14.0, "Gary Ballance"),
    (14.0, "Adam Lyth"),
    (14.0, "Ben Foakes"),
    (14.0, "Rory Burns"),
    (14.0, "Dom Sibley"),
    (15.0, "Finn Allen"),
    (15.0, "Will Young"),
    (15.0, "Henry Nicholls"),
    (15.0, "Tom Blundell"),
    (15.0, "Glenn Phillips"),
    (15.0, "Mark Chapman"),
    (15.0, "Jimmy Neesham"),
    (15.0, "Colin Munro"),
    (15.0, "Corey Anderson"),
    (15.0, "Mitchell McClenaghan"),
    (16.0, "Kyle Jamieson"),
    (16.0, "Adam Milne"),
    (16.0, "Blair Tickner"),
    (16.0, "Doug Bracewell"),
    (16.0, "Scott Kuggeleijn"),
    (16.0, "Ajaz Patel"),
    (16.0, "Will Somerville"),
    (16.0, "Hamish Rutherford"),
    (16.0, "George Worker"),
    (16.0, "Todd Astle"),
    (17.0, "Janneman Malan"),
    (17.0, "Kyle Verreynne"),
    (17.0, "Ryan Rickelton"),
    (17.0, "Sarel Erwee"),
    (17.0, "Keegan Petersen"),
    (17.0, "Khaya Zondo"),
    (17.0, "Zubayr Hamza"),
    (17.0, "Wiaan Mulder"),
    (17.0, "Dwaine Pretorius"),
    (17.0, "Andile Phehlukwayo"),
    (18.0, "Lizaad Williams"),
    (18.0, "Gerald Coetzee"),
    (18.0, "Marco Jansen"),
    (18.0, "Duanne Olivier"),
    (18.0, "Lutho Sipamla"),
    (18.0, "Beuran Hendricks"),
    (18.0, "Dane Paterson"),
    (18.0, "Dane Piedt"),
    (18.0, "Simon Harmer"),
    (18.0, "Tabraiz Shamsi"),
    (19.0, "Shamar Joseph"),
    (19.0, "Kevin Sinclair"),
    (19.0, "Alick Athanaze"),
    (19.0, "Kirk McKenzie"),
    (19.0, "Tagenarine Chanderpaul"),
    (19.0, "Gudakesh Motie"),
    (19.0, "Yannic Cariah"),
    (19.0, "Raymon Reifer"),
    (19.0, "Romario Shepherd"),
    (19.0, "Odean Smith"),
    (20.0, "Matthew Forde"),
    (20.0, "Sherfane Rutherford"),
    (20.0, "Akeal Hosein"),
    (20.0, "Dominic Drakes"),
    (20.0, "Nyeem Young"),
    (20.0, "Ashmead Nedd"),
    (20.0, "Joshua Da Silva"),
    (20.0, "Jomel Warrican"),
    (20.0, "Veerasammy Permaul"),
    (20.0, "Rahkeem Cornwall"),
]

def get_stats(rarity):
    """Generate health and attack stats based on rarity. Lower rarity = better stats."""
    max_stat = 250
    min_stat = 40
    max_rarity = 20.0
    stat = int(max_stat - ((rarity / max_rarity) * (max_stat - min_stat)))
    return stat, stat

added = 0
skipped = 0
for rarity, name in CRICKETERS:
    if Ball.objects.filter(country=name).exists():
        print(f"  SKIP (exists): {name}")
        skipped += 1
        continue

    health, attack = get_stats(rarity)

    Ball.objects.create(
        country=name,
        health=health,
        attack=attack,
        rarity=rarity,
        emoji_id=0,
        wild_card="premade_rvd_spawn.jpg",
        collection_card="premade_rvd.jpg",
        credits="CricStar",
        capacity_name="Cricket Legend",
        capacity_description=f"A legendary cricket card: {name}",
        capacity_logic={},
        enabled=True,
        tradeable=True,
        regime=regime,
        economy=economy,
    )
    print(f"  ADDED (rarity={rarity}): {name}  [HP={health}, ATK={attack}]")
    added += 1

print(f"\nDone! Added {added} cricketers, skipped {skipped} (already existed).")
print(f"Total cricketers in DB: {Ball.objects.count()}")
