# Generated by Django 6.0.3 on 2026-04-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0015_ball_spawnable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Logo identifier used in /cardmaker and /editcard commands (e.g. ICONS)', max_length=100, unique=True)),
                ('url', models.URLField(blank=True, default='', help_text='Optional URL to download the logo image from')),
                ('pathname', models.CharField(blank=True, default='', help_text='Optional local filename inside admin_panel/media/logos/ (e.g. ICONS.png)', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload a logo image directly', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos (Logo Maker)',
                'db_table': 'logo',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='ballinstance',
            name='server_id',
            field=models.BigIntegerField(blank=True, help_text='Discord server ID where this ball was caught', null=True),
        ),
        migrations.AlterField(
            model_name='ballinstance',
            name='spawned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ballinstance',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special'),
        ),
        migrations.AlterField(
            model_name='ballinstance',
            name='trade_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ballinstance_trade_player_set', to='bd_models.player'),
        ),
    ]
